=== KoheNC/l2emu/L2EmuProject-DataPack/data/templates/raid_spawns.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.l2jfree.com" xmlns="http://www.l2jfree.com"
	elementFormDefault="qualified">
	<xs:include schemaLocation="base.xsd" />
	<xs:element name="spawnList">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="spawn" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="spawn">
		<xs:complexType>
			<xs:attribute name="bossId" use="required" type="xs:integer" />
			<xs:attribute name="x" use="required" type="xs:integer" />
			<xs:attribute name="y" use="required" type="xs:integer" />
			<xs:attribute name="z" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/spawns/boss/raid_spawns.xml
<?xml version="1.0" encoding="UTF-8"?>
<spawnList xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ./../../../templates/raid_spawns.xsd">
	<spawn bossId="25001" x="-54416" y="146480" z="-2887" />
	<spawn bossId="25004" x="-94208" y="100240" z="-3520" />
	<spawn bossId="25007" x="124240" y="75376" z="-2800" />
	<spawn bossId="25010" x="113920" y="52960" z="-3735" />
	<spawn bossId="25013" x="169744" y="11920" z="-2732" />
	<spawn bossId="25016" x="76787" y="245775" z="-10376" />
	<spawn bossId="25019" x="7376" y="169376" z="-3600" />
	<spawn bossId="25020" x="90384" y="125568" z="-2128" />
	<spawn bossId="25023" x="27280" y="101744" z="-3696" />
	<spawn bossId="25026" x="92976" y="7920" z="-3914" />
	<spawn bossId="25029" x="54941" y="206705" z="-3728" />
	<spawn bossId="25032" x="88532" y="245798" z="-10376" />
	<spawn bossId="25035" x="180968" y="12035" z="-2720" />
	<spawn bossId="25038" x="-57360" y="186272" z="-4967" />
	<spawn bossId="25041" x="10416" y="126880" z="-3676" />
	<spawn bossId="25044" x="107792" y="27728" z="-3488" />
	<spawn bossId="25047" x="116352" y="27648" z="-3319" />
	<spawn bossId="25050" x="125520" y="27216" z="-3632" />
	<spawn bossId="25051" x="117760" y="-9072" z="-3264" />
	<spawn bossId="25054" x="113432" y="16403" z="3960" />
	<spawn bossId="25057" x="107056" y="168176" z="-3456" />
	<spawn bossId="25060" x="-60428" y="188264" z="-4512" />
	<spawn bossId="25063" x="-91024" y="116304" z="-3466" />
	<spawn bossId="25064" x="97223" y="94223" z="-3712" />
	<spawn bossId="25067" x="94992" y="-23168" z="-2176" />
	<spawn bossId="25070" x="125600" y="50100" z="-3600" />
	<spawn bossId="25073" x="143265" y="110044" z="-3944" />
	<spawn bossId="25076" x="-60976" y="127552" z="-2960" />
	<spawn bossId="25079" x="53712" y="102656" z="-1072" />
	<spawn bossId="25082" x="88512" y="140576" z="-3483" />
	<spawn bossId="25085" x="66944" y="67504" z="-3704" />
	<spawn bossId="25088" x="90848" y="16368" z="-5296" />
	<spawn bossId="25089" x="165424" y="93776" z="-2992" />
	<spawn bossId="25092" x="116151" y="16227" z="1944" />
	<spawn bossId="25095" x="-37856" y="198128" z="-2672" />
	<spawn bossId="25098" x="123536" y="133504" z="-3584" />
	<spawn bossId="25099" x="64048" y="16048" z="-3536" />
	<spawn bossId="25102" x="113840" y="84256" z="-2480" />
	<spawn bossId="25103" x="135872" y="94592" z="-3735" />
	<spawn bossId="25106" x="173880" y="-11412" z="-2880" />
	<spawn bossId="25109" x="152660" y="110387" z="-5520" />
	<spawn bossId="25112" x="116128" y="139392" z="-3640" />
	<spawn bossId="25115" x="125789" y="207644" z="-3752" />
	<spawn bossId="25118" x="50896" y="146576" z="-3645" />
	<spawn bossId="25119" x="121872" y="64032" z="-3536" />
	<spawn bossId="25122" x="86300" y="-8200" z="-3000" />
	<spawn bossId="25125" x="170656" y="85184" z="-2000" />
	<spawn bossId="25126" x="116263" y="15916" z="6992" />
	<spawn bossId="25127" x="-47552" y="219232" z="-2413" />
	<spawn bossId="25128" x="17696" y="179056" z="-3520" />
	<spawn bossId="25131" x="75488" y="-9360" z="-2720" />
	<spawn bossId="25134" x="95260" y="82042" z="-3712" />
	<spawn bossId="25137" x="125280" y="102576" z="-3305" />
	<spawn bossId="25143" x="113102" y="16002" z="6992" />
	<spawn bossId="25146" x="-13056" y="215680" z="-3760" />
	<spawn bossId="25149" x="-12656" y="138176" z="-3584" />
	<spawn bossId="25152" x="43872" y="123968" z="-2928" />
	<spawn bossId="25155" x="73520" y="66912" z="-3728" />
	<spawn bossId="25158" x="77104" y="5408" z="-3088" />
	<spawn bossId="25159" x="124984" y="43200" z="-3625" />
	<spawn bossId="25163" x="130500" y="59098" z="3584" />
	<spawn bossId="25166" x="-21800" y="152000" z="-2900" />
	<spawn bossId="25169" x="-54464" y="170288" z="-3136" />
	<spawn bossId="25170" x="26064" y="121808" z="-3738" />
	<spawn bossId="25173" x="75968" y="110784" z="-2512" />
	<spawn bossId="25176" x="92544" y="115232" z="-3200" />
	<spawn bossId="25179" x="167152" y="53120" z="-4148" />
	<spawn bossId="25182" x="41966" y="215417" z="-3728" />
	<spawn bossId="25185" x="99732" y="204331" z="-3784" />
	<spawn bossId="25188" x="127544" y="215264" z="-2960" />
	<spawn bossId="25189" x="127837" y="200661" z="-3792" />
	<spawn bossId="25192" x="125920" y="190208" z="-3291" />
	<spawn bossId="25198" x="102656" y="157424" z="-3735" />
	<spawn bossId="25199" x="108096" y="157408" z="-3688" />
	<spawn bossId="25202" x="119760" y="157392" z="-3744" />
	<spawn bossId="25205" x="123808" y="153408" z="-3671" />
	<spawn bossId="25208" x="109663" y="213615" z="-3624" />
	<spawn bossId="25211" x="113456" y="198118" z="-3689" />
	<spawn bossId="25214" x="111582" y="209341" z="-3687" />
	<spawn bossId="25217" x="89904" y="105712" z="-3292" />
	<spawn bossId="25220" x="113551" y="17083" z="-2120" />
	<spawn bossId="25223" x="43152" y="152352" z="-2848" />
	<spawn bossId="25226" x="104240" y="-3664" z="-3392" />
	<spawn bossId="25229" x="137568" y="-19488" z="-3552" />
	<spawn bossId="25230" x="66672" y="46704" z="-3920" />
	<spawn bossId="25233" x="185800" y="-26500" z="-2000" />
	<spawn bossId="25234" x="120080" y="111248" z="-3047" />
	<spawn bossId="25235" x="116400" y="-62528" z="-3264" />
	<spawn bossId="25238" x="155000" y="85400" z="-3200" />
	<spawn bossId="25241" x="165984" y="88048" z="-2384" />
	<spawn bossId="25244" x="171880" y="54868" z="-5992" />
	<spawn bossId="25245" x="188809" y="47780" z="-5968" />
	<spawn bossId="25248" x="127903" y="-13399" z="-3720" />
	<spawn bossId="25249" x="147104" y="-20560" z="-3377" />
	<spawn bossId="25252" x="192376" y="22087" z="-3608" />
	<spawn bossId="25255" x="170048" y="-24896" z="-3440" />
	<spawn bossId="25256" x="170320" y="42640" z="-4832" />
	<spawn bossId="25259" x="42050" y="208107" z="-3752" />
	<spawn bossId="25260" x="93120" y="19440" z="-3607" />
	<spawn bossId="25263" x="144400" y="-28192" z="-1920" />
	<spawn bossId="25266" x="188983" y="13647" z="-2672" />
	<spawn bossId="25269" x="123504" y="-23696" z="-3481" />
	<spawn bossId="25272" x="49248" y="127792" z="-3552" />
	<spawn bossId="25276" x="154088" y="-14116" z="-3736" />
	<spawn bossId="25277" x="54651" y="180269" z="-4976" />
	<spawn bossId="25280" x="85622" y="88766" z="-5120" />
	<spawn bossId="25281" x="151053" y="88124" z="-5424" />
	<spawn bossId="25282" x="179311" y="-7632" z="-4896" />
	<spawn bossId="25293" x="134672" y="-115600" z="-1216" />
	<spawn bossId="25299" x="148160" y="-73808" z="-4919" />
	<spawn bossId="25302" x="145504" y="-81664" z="-6016" />
	<spawn bossId="25305" x="145008" y="-84992" z="-6240" />
	<spawn bossId="25309" x="115552" y="-39200" z="-2480" />
	<spawn bossId="25312" x="109216" y="-36160" z="-938" />
	<spawn bossId="25315" x="105584" y="-43024" z="-1728" />
	<spawn bossId="25319" x="184542" y="-106330" z="-6304" />
	<spawn bossId="25322" x="93296" y="-75104" z="-1824" />
	<spawn bossId="25325" x="91008" y="-85904" z="-2736" />
	<spawn bossId="25328" x="59331" y="-42403" z="-3003" />
	<spawn bossId="25352" x="-16912" y="174912" z="-3264" />
	<spawn bossId="25354" x="-16096" y="184288" z="-3817" />
	<spawn bossId="25357" x="-3456" y="112864" z="-3456" />
	<spawn bossId="25360" x="29216" y="179280" z="-3624" />
	<spawn bossId="25362" x="-55920" y="186768" z="-3336" />
	<spawn bossId="25365" x="-62000" y="190256" z="-3687" />
	<spawn bossId="25366" x="-62368" y="179440" z="-3594" />
	<spawn bossId="25369" x="-45616" y="111024" z="-3808" />
	<spawn bossId="25372" x="48000" y="243376" z="-6611" />
	<spawn bossId="25373" x="9649" y="77467" z="-3808" />
	<spawn bossId="25375" x="22500" y="80300" z="-2772" />
	<spawn bossId="25378" x="-54096" y="84288" z="-3512" />
	<spawn bossId="25380" x="-47367" y="51548" z="-5904" />
	<spawn bossId="25383" x="51632" y="153920" z="-3552" />
	<spawn bossId="25385" x="53600" y="143472" z="-3872" />
	<spawn bossId="25388" x="40128" y="101920" z="-1241" />
	<spawn bossId="25391" x="45600" y="120592" z="-2455" />
	<spawn bossId="25392" x="29928" y="107160" z="-3708" />
	<spawn bossId="25394" x="129481" y="219722" z="-3600" />
	<spawn bossId="25395" x="15000" y="119000" z="-11900" />
	<spawn bossId="25398" x="5000" y="189000" z="-3728" />
	<spawn bossId="25401" x="117808" y="102880" z="-3600" />
	<spawn bossId="25404" x="35992" y="191312" z="-3104" />
	<spawn bossId="25407" x="115072" y="112272" z="-3018" />
	<spawn bossId="25410" x="72192" y="125424" z="-3657" />
	<spawn bossId="25412" x="81920" y="113136" z="-3056" />
	<spawn bossId="25415" x="128352" y="138464" z="-3467" />
	<spawn bossId="25418" x="62416" y="8096" z="-3376" />
	<spawn bossId="25420" x="42032" y="24128" z="-4704" />
	<spawn bossId="25423" x="113600" y="47120" z="-4640" />
	<spawn bossId="25426" x="-18048" y="-101264" z="-2112" />
	<spawn bossId="25429" x="172064" y="-214752" z="-3565" />
	<spawn bossId="25431" x="79648" y="18320" z="-5232" />
	<spawn bossId="25434" x="104096" y="-16896" z="-1803" />
	<spawn bossId="25437" x="67296" y="64128" z="-3723" />
	<spawn bossId="25438" x="107000" y="92000" z="-2272" />
	<spawn bossId="25441" x="111440" y="82912" z="-2912" />
	<spawn bossId="25444" x="113232" y="17456" z="-4384" />
	<spawn bossId="25447" x="113200" y="17552" z="-1424" />
	<spawn bossId="25450" x="113600" y="15104" z="9559" />
	<spawn bossId="25453" x="156704" y="-6096" z="-4185" />
	<spawn bossId="25456" x="133632" y="87072" z="-3623" />
	<spawn bossId="25460" x="150304" y="67776" z="-3688" />
	<spawn bossId="25463" x="166288" y="68096" z="-3264" />
	<spawn bossId="25473" x="175712" y="29856" z="-3776" />
	<spawn bossId="25475" x="183568" y="24560" z="-3184" />
	<spawn bossId="25478" x="168288" y="28368" z="-3632" />
	<spawn bossId="25481" x="53517" y="205413" z="-3728" />
	<spawn bossId="25484" x="43160" y="220463" z="-3680" />
	<spawn bossId="25493" x="83174" y="254428" z="-10873" />
	<spawn bossId="25496" x="88300" y="258000" z="-10200" />
