=== KoheNC/l2emu/L2EmuProject-DataPack/data/templates/transformSkillTree.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.l2jfree.com" xmlns="http://www.l2jfree.com"
	elementFormDefault="qualified">
	<xs:include schemaLocation="base.xsd" />
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="transform" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="transform">
		<xs:complexType>
			<xs:attribute name="item_id" use="required" type="xs:integer" />
			<xs:attribute name="level" use="required" type="xs:integer" />
			<xs:attribute name="min_level" use="required" type="xs:integer" />
			<xs:attribute name="name" use="required" />
			<xs:attribute name="race_id" use="required" type="xs:integer" />
			<xs:attribute name="skill_id" use="required" type="xs:integer" />
			<xs:attribute name="sp" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/char_data/skill_tree/transform_skill_tree.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/transformSkillTree.xsd">
	<transform race_id="-1" skill_id="617" item_id="9648" level="1"
		name="Transform Onyx Beast" sp="0" min_level="50" />
	<transform race_id="-1" skill_id="618" item_id="9649" level="1"
		name="Transform Death Blader" sp="0" min_level="55" />
	<transform race_id="-1" skill_id="663" item_id="10295" level="1"
		name="Transfomr Zaken" sp="0" min_level="60" />
	<transform race_id="-1" skill_id="664" item_id="10296" level="1"
		name="Transform Anakim" sp="0" min_level="70" />
	<transform race_id="-1" skill_id="665" item_id="10297" level="1"
		name="Transform Benom" sp="0" min_level="70" />
	<transform race_id="-1" skill_id="666" item_id="10298" level="1"
		name="Transform Gordon" sp="0" min_level="76" />
	<transform race_id="-1" skill_id="667" item_id="10299" level="1"
		name="Transform Ranku" sp="0" min_level="76" />
	<transform race_id="-1" skill_id="668" item_id="10300" level="1"
		name="Transform Kiyachi" sp="0" min_level="76" />
	<transform race_id="-1" skill_id="669" item_id="10301" level="1"
		name="Transform Demon Prince" sp="0" min_level="76" />
	<transform race_id="-1" skill_id="670" item_id="10302" level="1"
		name="Transform Heretic" sp="0" min_level="70" />
	<transform race_id="-1" skill_id="671" item_id="10303" level="1"
		name="Transform Vale Master" sp="0" min_level="70" />
	<transform race_id="-1" skill_id="672" item_id="10304" level="1"
		name="Transform Saber Tooth Tiger" sp="0" min_level="70" />
	<transform race_id="-1" skill_id="673" item_id="10305" level="1"
		name="Transform Ol Mahum" sp="0" min_level="70" />
	<transform race_id="-1" skill_id="674" item_id="10306" level="1"
		name="Transform Doll Blader" sp="0" min_level="70" />
	<transform race_id="0" skill_id="541" item_id="9650" level="1"
		name="Transform Grail Apostle" sp="0" min_level="60" />
	<transform race_id="0" skill_id="545" item_id="9651" level="1"
		name="Transform Unicorn" sp="0" min_level="60" />
	<transform race_id="0" skill_id="548" item_id="9652" level="1"
		name="Transform Lilim Knight" sp="0" min_level="60" />
	<transform race_id="0" skill_id="551" item_id="9653" level="1"
		name="Transform Golem Guardian" sp="0" min_level="60" />
	<transform race_id="0" skill_id="554" item_id="9654" level="1"
		name="Transform Inferno Drake" sp="0" min_level="60" />
	<transform race_id="0" skill_id="558" item_id="9655" level="1"
		name="Transform Dragon Bomber" sp="0" min_level="60" />
	<transform race_id="1" skill_id="542" item_id="9650" level="1"
		name="Transform Grail Apostle" sp="0" min_level="60" />
	<transform race_id="1" skill_id="544" item_id="9651" level="1"
		name="Transform Unicorn" sp="0" min_level="60" />
	<transform race_id="1" skill_id="549" item_id="9652" level="1"
		name="Transform Lilim Knight" sp="0" min_level="60" />
	<transform race_id="1" skill_id="551" item_id="9653" level="1"
		name="Transform Golem Guardian" sp="0" min_level="60" />
	<transform race_id="1" skill_id="554" item_id="9654" level="1"
		name="Transform Inferno Drake" sp="0" min_level="60" />
	<transform race_id="1" skill_id="557" item_id="9655" level="1"
		name="Transform Dragon Bomber" sp="0" min_level="60" />
	<transform race_id="2" skill_id="542" item_id="9650" level="1"
		name="Transform Grail Apostle" sp="0" min_level="60" />
	<transform race_id="2" skill_id="546" item_id="9651" level="1"
		name="Transform Unicorn" sp="0" min_level="60" />
	<transform race_id="2" skill_id="547" item_id="9652" level="1"
		name="Transform Lilim Knight" sp="0" min_level="60" />
	<transform race_id="2" skill_id="551" item_id="9653" level="1"
		name="Transform Golem Guardian" sp="0" min_level="60" />
	<transform race_id="2" skill_id="554" item_id="9654" level="1"
		name="Transform Inferno Drake" sp="0" min_level="60" />
	<transform race_id="2" skill_id="557" item_id="9655" level="1"
		name="Transform Dragon Bomber" sp="0" min_level="60" />
	<transform race_id="3" skill_id="542" item_id="9650" level="1"
		name="Transform Grail Apostle" sp="0" min_level="60" />
	<transform race_id="3" skill_id="545" item_id="9651" level="1"
		name="Transform Unicorn" sp="0" min_level="60" />
	<transform race_id="3" skill_id="548" item_id="9652" level="1"
		name="Transform Lilim Knight" sp="0" min_level="60" />
	<transform race_id="3" skill_id="552" item_id="9653" level="1"
		name="Transform Golem Guardian" sp="0" min_level="60" />
	<transform race_id="3" skill_id="553" item_id="9654" level="1"
		name="Transform Inferno Drake" sp="0" min_level="60" />
	<transform race_id="3" skill_id="557" item_id="9655" level="1"
		name="Transform Dragon Bomber" sp="0" min_level="60" />
	<transform race_id="4" skill_id="542" item_id="9650" level="1"
		name="Transform Grail Apostle" sp="0" min_level="60" />
	<transform race_id="4" skill_id="545" item_id="9651" level="1"
		name="Transform Unicorn" sp="0" min_level="60" />
	<transform race_id="4" skill_id="548" item_id="9652" level="1"
		name="Transform Lilim Knight" sp="0" min_level="60" />
	<transform race_id="4" skill_id="550" item_id="9653" level="1"
		name="Transform Golem Guardian" sp="0" min_level="60" />
	<transform race_id="4" skill_id="555" item_id="9654" level="1"
		name="Transform Inferno Drake" sp="0" min_level="60" />
	<transform race_id="4" skill_id="557" item_id="9655" level="1"
		name="Transform Dragon Bomber" sp="0" min_level="60" />
	<transform race_id="5" skill_id="543" item_id="9650" level="1"
		name="Transform Grail Apostle" sp="0" min_level="60" />
	<transform race_id="5" skill_id="545" item_id="9651" level="1"
		name="Transform Unicorn" sp="0" min_level="60" />
	<transform race_id="5" skill_id="548" item_id="9652" level="1"
		name="Transform Lilim Knight" sp="0" min_level="60" />
	<transform race_id="5" skill_id="551" item_id="9653" level="1"
		name="Transform Golem Guardian" sp="0" min_level="60" />
	<transform race_id="5" skill_id="554" item_id="9654" level="1"
		name="Transform Inferno Drake" sp="0" min_level="60" />
	<transform race_id="5" skill_id="556" item_id="9655" level="1"
		name="Transform Dragon Bomber" sp="0" min_level="60" />
</list>
