=== KoheNC/l2emu/L2EmuProject-DataPack/data/templates/walkerRoutes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.l2jfree.com" xmlns="http://www.l2jfree.com"
	elementFormDefault="qualified">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="npc" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="npc">
		<xs:complexType>
			<xs:attribute name="chatText" use="required" />
			<xs:attribute name="delay" use="required" type="xs:integer" />
			<xs:attribute name="move_point" use="required" type="xs:integer" />
			<xs:attribute name="move_x" use="required" type="xs:integer" />
			<xs:attribute name="move_y" use="required" type="xs:integer" />
			<xs:attribute name="move_z" use="required" type="xs:integer" />
			<xs:attribute name="npc_id" use="required" type="xs:integer" />
			<xs:attribute name="route_id" use="required" type="xs:integer" />
			<xs:attribute name="running" use="required" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/walker_routes.xml
<?xml version="1.0" standalone="yes"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../templates/walkerRoutes.xsd">
	<npc route_id="1" npc_id="31361" move_point="1" chatText="" move_x="22418"
		move_y="10249" move_z="-3648" delay="61" running="true" />
	<npc route_id="1" npc_id="31361" move_point="2" chatText="" move_x="23423"
		move_y="11165" move_z="-3720" delay="0" running="true" />
	<npc route_id="1" npc_id="31361" move_point="3" chatText="" move_x="20182"
		move_y="11101" move_z="-3720" delay="0" running="true" />
	<npc route_id="1" npc_id="31361" move_point="4" chatText="" move_x="17327"
		move_y="13603" move_z="-3728" delay="1" running="true" />
	<npc route_id="1" npc_id="31361" move_point="5"
		chatText="The mass of darkness will start in a couple of days. Pay more attention to the guard!"
		move_x="17410" move_y="13038" move_z="-3736" delay="10" running="true" />
	<npc route_id="1" npc_id="31361" move_point="6" chatText="" move_x="20176"
		move_y="12902" move_z="-3712" delay="0" running="true" />
	<npc route_id="1" npc_id="31361" move_point="7" chatText="" move_x="21669"
		move_y="13378" move_z="-3616" delay="0" running="true" />
	<npc route_id="1" npc_id="31361" move_point="8" chatText="" move_x="20675"
		move_y="10401" move_z="-3712" delay="0" running="true" />
	<npc route_id="2" npc_id="31360" move_point="1" chatText="" move_x="10820"
		move_y="14770" move_z="-4240" delay="62" running="false" />
	<npc route_id="2" npc_id="31360" move_point="2" chatText="" move_x="10947"
		move_y="14642" move_z="-4240" delay="0" running="false" />
	<npc route_id="2" npc_id="31360" move_point="3" chatText="" move_x="11301"
		move_y="15844" move_z="-4584" delay="0" running="false" />
	<npc route_id="2" npc_id="31360" move_point="4" chatText="" move_x="12107"
		move_y="16431" move_z="-4584" delay="0" running="false" />
	<npc route_id="2" npc_id="31360" move_point="5"
		chatText="You&apos;re a hard worker,Rayla!" move_x="15097" move_y="15662"
		move_z="-4376" delay="6" running="false" />
	<npc route_id="2" npc_id="31360" move_point="6" chatText="" move_x="15269"
		move_y="16281" move_z="-4376" delay="7" running="false" />
	<npc route_id="2" npc_id="31360" move_point="7" chatText="" move_x="12336"
		move_y="16921" move_z="-4584" delay="0" running="false" />
	<npc route_id="2" npc_id="31360" move_point="8" chatText="" move_x="11786"
		move_y="17663" move_z="-4564" delay="0" running="false" />
	<npc route_id="2" npc_id="31360" move_point="9" chatText="" move_x="11246"
		move_y="17650" move_z="-4568" delay="0" running="false" />
	<npc route_id="2" npc_id="31360" move_point="10" chatText=""
		move_x="10649" move_y="17284" move_z="-4584" delay="0" running="false" />
	<npc route_id="2" npc_id="31360" move_point="11"
		chatText="You&apos;re a hard worker!" move_x="7692" move_y="18041"
		move_z="-4376" delay="6" running="false" />
	<npc route_id="2" npc_id="31360" move_point="12" chatText=""
		move_x="10549" move_y="16780" move_z="-4584" delay="0" running="false" />
	<npc route_id="2" npc_id="31360" move_point="13" chatText=""
		move_x="10722" move_y="16538" move_z="-4584" delay="0" running="false" />
	<npc route_id="2" npc_id="31360" move_point="14" chatText=""
		move_x="11008" move_y="15927" move_z="-4584" delay="0" running="false" />
	<npc route_id="3" npc_id="31362" move_point="1"
		chatText="Mr. Lid, Murdoc, and Airy! How are you doing?" move_x="114847"
		move_y="-180066" move_z="-877" delay="30" running="false" />
	<npc route_id="3" npc_id="31362" move_point="2" chatText="" move_x="114834"
		move_y="-179685" move_z="-877" delay="2" running="false" />
	<npc route_id="3" npc_id="31362" move_point="3" chatText="" move_x="116122"
		move_y="-179457" move_z="-1068" delay="1" running="false" />
	<npc route_id="3" npc_id="31362" move_point="4" chatText="" move_x="116798"
		move_y="-180391" move_z="-1200" delay="2" running="false" />
	<npc route_id="3" npc_id="31362" move_point="5" chatText="" move_x="116324"
		move_y="-181564" move_z="-1384" delay="2" running="false" />
	<npc route_id="3" npc_id="31362" move_point="6" chatText="" move_x="115797"
		move_y="-181563" move_z="-1336" delay="0" running="false" />
	<npc route_id="3" npc_id="31362" move_point="7" chatText="Care to go a round?"
		move_x="116054" move_y="-181575" move_z="-1352" delay="0" running="false" />
	<npc route_id="3" npc_id="31362" move_point="8" chatText="" move_x="116506"
		move_y="-181478" move_z="-1384" delay="2" running="false" />
	<npc route_id="3" npc_id="31362" move_point="9" chatText="" move_x="116634"
		move_y="-180029" move_z="-1160" delay="1" running="false" />
	<npc route_id="3" npc_id="31362" move_point="10" chatText=""
		move_x="115347" move_y="-178623" move_z="-928" delay="1" running="false" />
	<npc route_id="3" npc_id="31362" move_point="11" chatText=""
		move_x="115763" move_y="-177591" move_z="-888" delay="2" running="false" />
	<npc route_id="3" npc_id="31362" move_point="12"
		chatText="Have a nice day, Mr. Garita and Mion!" move_x="115801"
		move_y="-177342" move_z="-880" delay="1" running="false" />
	<npc route_id="3" npc_id="31362" move_point="13" chatText=""
		move_x="115869" move_y="-177340" move_z="-880" delay="15" running="false" />
	<npc route_id="3" npc_id="31362" move_point="14" chatText=""
		move_x="115788" move_y="-177482" move_z="-880" delay="3" running="false" />
	<npc route_id="3" npc_id="31362" move_point="15" chatText=""
		move_x="115124" move_y="-179821" move_z="-885" delay="1" running="false" />
	<npc route_id="3" npc_id="31362" move_point="16" chatText=""
		move_x="115103" move_y="-180065" move_z="-877" delay="1" running="false" />
	<npc route_id="4" npc_id="31363" move_point="1"
		chatText="Where is that fool hiding?" move_x="116731" move_y="-182477"
		move_z="-1512" delay="10" running="true" />
	<npc route_id="4" npc_id="31363" move_point="2" chatText="" move_x="115870"
		move_y="-183280" move_z="-1472" delay="0" running="true" />
	<npc route_id="4" npc_id="31363" move_point="3" chatText="" move_x="115746"
		move_y="-183428" move_z="-1472" delay="1" running="true" />
	<npc route_id="4" npc_id="31363" move_point="4" chatText="" move_x="115870"
		move_y="-183280" move_z="-1472" delay="1" running="true" />
	<npc route_id="4" npc_id="31363" move_point="5" chatText="" move_x="115999"
		move_y="-183246" move_z="-1480" delay="0" running="true" />
	<npc route_id="4" npc_id="31363" move_point="6" chatText="" move_x="116094"
		move_y="-183113" move_z="-1480" delay="1" running="true" />
	<npc route_id="4" npc_id="31363" move_point="7"
		chatText="Have you seen Torocco today?" move_x="116584" move_y="-184294"
		move_z="-1568" delay="11" running="true" />
	<npc route_id="4" npc_id="31363" move_point="8" chatText="" move_x="116392"
		move_y="-184100" move_z="-1560" delay="1" running="true" />
	<npc route_id="4" npc_id="31363" move_point="9" chatText="" move_x="117093"
		move_y="-182524" move_z="-1528" delay="1" running="true" />
	<npc route_id="4" npc_id="31363" move_point="10"
		chatText="Have you seen Torocco?" move_x="117789" move_y="-182540"
		move_z="-1528" delay="11" running="true" />
	<npc route_id="5" npc_id="31359" move_point="1" chatText="" move_x="45744"
		move_y="50561" move_z="-3065" delay="61" running="false" />
	<npc route_id="5" npc_id="31359" move_point="2" chatText="" move_x="46444"
		move_y="49742" move_z="-3065" delay="2" running="false" />
	<npc route_id="5" npc_id="31359" move_point="3"
		chatText="How can we save the Mother Tree?" move_x="46103" move_y="48798"
		move_z="-3065" delay="5" running="false" />
	<npc route_id="5" npc_id="31359" move_point="4"
		chatText="The Mother Tree is slowly dying" move_x="45403" move_y="48436"
		move_z="-3065" delay="5" running="false" />
	<npc route_id="5" npc_id="31359" move_point="5" chatText="" move_x="44444"
		move_y="49078" move_z="-3065" delay="0" running="false" />
	<npc route_id="5" npc_id="31359" move_point="6" chatText="" move_x="44414"
		move_y="50025" move_z="-3065" delay="0" running="false" />
	<npc route_id="5" npc_id="31359" move_point="7" chatText="" move_x="44957"
		move_y="50568" move_z="-3065" delay="0" running="false" />
	<npc route_id="5" npc_id="31359" move_point="8" chatText="" move_x="44414"
		move_y="50025" move_z="-3065" delay="0" running="false" />
	<npc route_id="5" npc_id="31359" move_point="9" chatText="" move_x="44444"
		move_y="49078" move_z="-3065" delay="0" running="false" />
	<npc route_id="5" npc_id="31359" move_point="10"
		chatText="The Mother Tree is slowly dying" move_x="45403" move_y="48436"
		move_z="-3065" delay="5" running="false" />
	<npc route_id="5" npc_id="31359" move_point="11"
		chatText="How can we save the Mother Tree?" move_x="46103" move_y="48798"
		move_z="-3065" delay="5" running="false" />
	<npc route_id="5" npc_id="31359" move_point="12" chatText=""
		move_x="46444" move_y="49742" move_z="-3065" delay="2" running="false" />
	<npc route_id="6" npc_id="31358" move_point="1"
		chatText="Lady Mirabel, may the peace of the lake be with you!"
		move_x="47015" move_y="51278" move_z="-2992" delay="65" running="false" />
	<npc route_id="6" npc_id="31358" move_point="2" chatText="" move_x="47437"
		move_y="50441" move_z="-2992" delay="0" running="false" />
	<npc route_id="6" npc_id="31358" move_point="3" chatText="" move_x="47509"
		move_y="49038" move_z="-2992" delay="0" running="false" />
	<npc route_id="6" npc_id="31358" move_point="4" chatText="" move_x="46725"
		move_y="47755" move_z="-2992" delay="0" running="false" />
	<npc route_id="6" npc_id="31358" move_point="5"
		chatText="The Mother Tree is always so gorgeous!" move_x="45319"
		move_y="47339" move_z="-2992" delay="5" running="false" />
	<npc route_id="6" npc_id="31358" move_point="6" chatText="" move_x="43998"
