=== KoheNC/l2emu/L2EmuProject-DataPack/data/static_data/templates/teleport.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.l2jfree.com" xmlns="http://www.l2jfree.com"
	elementFormDefault="qualified">
	<xs:include schemaLocation="base.xsd" />
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="teleport" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="teleport">
		<xs:complexType>
			<xs:attribute name="description" use="required" />
			<xs:attribute name="id" use="required" type="xs:integer" />
			<xs:attribute name="isNoble" use="required" type="xs:boolean" />
			<xs:attribute name="locX" use="required" type="xs:integer" />
			<xs:attribute name="locY" use="required" type="xs:integer" />
			<xs:attribute name="locZ" use="required" type="xs:integer" />
			<xs:attribute name="price" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/teleport/Innadril.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../templates/teleport.xsd">
	<teleport id="2027" description="Innadril Outer -> Out" locX="116263"
		locY="245174" locZ="-1058" price="0" isNoble="false" />
	<teleport id="2028" description="Innadril Outer -> In" locX="116263"
		locY="245750" locZ="-1058" price="0" isNoble="false" />
	<teleport id="2029" description="Innadril Inner -> Out" locX="116021"
		locY="247821" locZ="-826" price="0" isNoble="false" />
	<teleport id="2030" description="Innadril Inner -> In" locX="116021"
		locY="248272" locZ="-805" price="0" isNoble="false" />
	<teleport id="13040" description="Innadril Castle -> Front Of Innadril Castle"
		locX="118795" locY="219276" locZ="-3611" price="0" isNoble="false" />
	<teleport id="13041" description="Innadril Castle -> Innadril Town Square"
		locX="110788" locY="220506" locZ="-3697" price="0" isNoble="false" />
	<teleport id="13042"
		description="Innadril Castle -> Front of the White Sands Fortress"
		locX="124542" locY="207762" locZ="-3240" price="0" isNoble="false" />
	<teleport id="13043"
		description="Innadril Castle -> The Center of Alligator Island" locX="113708"
		locY="178387" locZ="-3232" price="500" isNoble="false" />
	<teleport id="13044" description="Innadril Castle -> Field of Silence"
		locX="75387" locY="195263" locZ="-3000" price="500" isNoble="false" />
	<teleport id="13045" description="Innadril Castle -> Field of Whispers"
		locX="97786" locY="209303" locZ="-3040" price="500" isNoble="false" />
	<teleport id="13046" description="Innadril Castle -> Inside the Garden of Eva"
		locX="82693" locY="242220" locZ="-6712" price="500" isNoble="false" />
	<teleport id="15000" description="Innadril(artifact -> out)"
		locX="116046" locY="247094" locZ="-930" price="0" isNoble="false" />
	<teleport id="15001" description="Innadril(artifact -> hall)"
		locX="116028" locY="249163" locZ="-787" price="0" isNoble="false" />
	<teleport id="15002" description="Innadril(artifact -> outofcastle)"
		locX="116373" locY="244729" locZ="-1059" price="0" isNoble="false" />
	<teleport id="15003" description="Innadril(hall -> artifact)"
		locX="116028" locY="250136" locZ="-867" price="0" isNoble="false" />
	<teleport id="15004" description="Innadril(hall -> out)" locX="116046"
		locY="247094" locZ="-930" price="0" isNoble="false" />
	<teleport id="15005" description="Innadril(hall -> outofcastle)"
		locX="116373" locY="244729" locZ="-1059" price="0" isNoble="false" />
	<teleport id="15006" description="Innadril(out -> artifact)"
		locX="116028" locY="250136" locZ="-867" price="0" isNoble="false" />
	<teleport id="15007" description="Innadril(out -> hall)" locX="116028"
		locY="249163" locZ="-787" price="0" isNoble="false" />
	<teleport id="15008" description="Innadril(out -> outofcastle)"
		locX="116373" locY="244729" locZ="-1059" price="0" isNoble="false" />
	<teleport id="15009" description="Innadril(outofcastle -> artifact)"
		locX="116028" locY="250136" locZ="-867" price="0" isNoble="false" />
	<teleport id="15010" description="Innadril(outofcastle -> out)"
		locX="116046" locY="247094" locZ="-930" price="0" isNoble="false" />
	<teleport id="15011" description="Innadril(outofcastle -> hall)"
		locX="116028" locY="249163" locZ="-787" price="0" isNoble="false" />
	<teleport id="60018" description="Innadril Throne" locX="116025"
		locY="249097" locZ="-787" price="0" isNoble="false" />
	<teleport id="60019" description="Innadril Inside" locX="116026"
		locY="246975" locZ="-967" price="0" isNoble="false" />
	<teleport id="60020" description="Innadril Artefacts Room"
		locX="116033" locY="250158" locZ="-867" price="0" isNoble="false" />
	<teleport id="60021" description="Innadril Out of the Castle"
		locX="116265" locY="244631" locZ="-1057" price="0" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/teleport/Necro.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/teleport.xsd">
	<teleport id="262" description="Necro Sacrifice Entrance"
		locX="-41570" locY="209785" locZ="-5089" price="0" isNoble="false" />
	<teleport id="263" description="Necro Sacrifice Exit" locX="-41567"
		locY="209292" locZ="-5091" price="0" isNoble="false" />
	<teleport id="264" description="Necro Pilgrims Entrance" locX="45251"
		locY="123890" locZ="-5415" price="0" isNoble="false" />
	<teleport id="265" description="Necro Pilgrims Exit" locX="45250"
		locY="124366" locZ="-5417" price="0" isNoble="false" />
	<teleport id="266" description="Necro Worshippers Entrance"
		locX="111273" locY="174015" locZ="-5417" price="0" isNoble="false" />
	<teleport id="267" description="Necro Worshippers Exit" locX="110818"
		locY="174010" locZ="-5443" price="0" isNoble="false" />
	<teleport id="268" description="Necro Patriots Entrance" locX="-21726"
		locY="77385" locZ="-5177" price="0" isNoble="false" />
	<teleport id="269" description="Necro Patriots Exit" locX="-22197"
		locY="77369" locZ="-5177" price="0" isNoble="false" />
	<teleport id="270" description="Necro Ascetics Entrance" locX="-52254"
		locY="79103" locZ="-4743" price="0" isNoble="false" />
	<teleport id="271" description="Necro Ascetics Exit" locX="-52716"
		locY="79106" locZ="-4745" price="0" isNoble="false" />
	<teleport id="272" description="Necro Martyrs Entrance" locX="118308"
		locY="132800" locZ="-4833" price="0" isNoble="false" />
	<teleport id="273" description="Necro Martyrs Exit" locX="117793"
		locY="132810" locZ="-4835" price="0" isNoble="false" />
	<teleport id="274" description="Necro Saints Entrance" locX="83000"
		locY="209213" locZ="-5443" price="0" isNoble="false" />
	<teleport id="275" description="Necro Saints Exit" locX="82608"
		locY="209225" locZ="-5443" price="0" isNoble="false" />
	<teleport id="276" description="Necro Disciples Entrance"
		locX="172251" locY="-17605" locZ="-4903" price="0" isNoble="false" />
	<teleport id="277" description="Necro Disciples Exit" locX="171902"
		locY="-17595" locZ="-4905" price="0" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/teleport/Dion.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/teleport.xsd">
	<teleport id="18" description="Dion Town -> Town of Gludio"
		locX="-12672" locY="122776" locZ="-3116" price="3400" isNoble="false" />
	<teleport id="19" description="Dion Town -> Town of Giran"
		locX="83400" locY="147943" locZ="-3404" price="6800" isNoble="false" />
	<teleport id="20" description="Dion Town -> Giran Harbor"
		locX="47942" locY="186764" locZ="-3485" price="6500" isNoble="false" />
	<teleport id="85" description="Dion -> Heine" locX="111409"
		locY="219364" locZ="-3545" price="12000" isNoble="false" />
	<teleport id="86" description="Dion -> Partisan Hideaway"
		locX="46467" locY="126885" locZ="-3720" price="1700" isNoble="false" />
	<teleport id="87" description="Dion -> Bee Hive" locX="20505"
		locY="189036" locZ="-3344" price="2900" isNoble="false" />
	<teleport id="350" description="Dion(artifact -> out)" locX="22967"
		locY="157715" locZ="-2954" price="0" isNoble="false" />
	<teleport id="351" description="Dion(artifact -> hall)" locX="22090"
		locY="159871" locZ="-2711" price="0" isNoble="false" />
	<teleport id="352" description="Dion(artifact -> outofcastle)"
		locX="22448" locY="155798" locZ="-2958" price="0" isNoble="false" />
	<teleport id="353" description="Dion(in -> artifact)" locX="22592"
		locY="161530" locZ="-2775" price="0" isNoble="false" />
	<teleport id="354" description="Dion(in -> out)" locX="22967"
		locY="157715" locZ="-2954" price="0" isNoble="false" />
	<teleport id="355" description="Dion(in -> outofcastle)" locX="22448"
		locY="155798" locZ="-2958" price="0" isNoble="false" />
	<teleport id="356" description="Dion(out -> artifact)" locX="22592"
		locY="161530" locZ="-2775" price="0" isNoble="false" />
	<teleport id="357" description="Dion(out -> hall)" locX="22090"
		locY="159871" locZ="-2711" price="0" isNoble="false" />
	<teleport id="358" description="Dion(out -> outofcastle)"
		locX="22448" locY="155798" locZ="-2958" price="0" isNoble="false" />
	<teleport id="359" description="Dion(outofcastle -> artifact)"
		locX="22592" locY="161530" locZ="-2775" price="0" isNoble="false" />
	<teleport id="360" description="Dion(outofcastle -> out)"
		locX="22967" locY="157715" locZ="-2954" price="0" isNoble="false" />
	<teleport id="361" description="Dion(outofcastle -> hall)"
		locX="22090" locY="159871" locZ="-2711" price="0" isNoble="false" />
	<teleport id="1046" description="Dion -> Goddard" locX="147928"
		locY="-55273" locZ="-2734" price="71000" isNoble="false" />
	<teleport id="1047" description="Dion -> Rune Castle Town"
		locX="43799" locY="-47727" locZ="-798" price="57000" isNoble="false" />
	<teleport id="1048" description="Dion -> Schuttgart" locX="87386"
		locY="-143246" locZ="-1293" price="88000" isNoble="false" />
	<teleport id="1049" description="Dion -> Aden" locX="146819" 
		locY="25806" locZ="-2013" price="52000" isNoble="false" />
	<teleport id="1050" description="Dion -> Oren" locX="82956"
		locY="53162" locZ="-1495" price="33000" isNoble="false" />
	<teleport id="1051" description="Dion -> Cruma Marshlands"
		locX="5106" locY="126916" locZ="-3664" price="760" isNoble="false" />
	<teleport id="1052" description="Dion -> Cruma Tower" locX="17192"
		locY="114178" locZ="-3439" price="2300" isNoble="false" />
	<teleport id="1053" description="Dion -> Dion Pasture" locX="630"
		locY="179184" locZ="-3720" price="1500" isNoble="false" />
	<teleport id="1054" description="Dion -> Tanor Canyon" locX="60374"
		locY="164301" locZ="-2856" price="3900" isNoble="false" />
	<teleport id="2005" description="Dion Outer -> Out" locX="22315"
		locY="156447" locZ="-2962" price="0" isNoble="false" />
	<teleport id="2006" description="Dion Outer -> In" locX="22315"
		locY="156909" locZ="-2962" price="0" isNoble="false" />
	<teleport id="2007" description="Dion Inner -> Out" locX="22073"
		locY="159057" locZ="-2725" price="0" isNoble="false" />
	<teleport id="2008" description="Dion Inner -> In" locX="22073"
		locY="159516" locZ="-2706" price="0" isNoble="false" />
	<teleport id="13008" description="Dion Castle -> Front Of Dion Castle"
		locX="17433" locY="147442" locZ="-3147" price="0" isNoble="false" />
	<teleport id="13009" description="Dion Castle -> Dion Town Square"
		locX="18643" locY="145420" locZ="-3152" price="0" isNoble="false" />
	<teleport id="13010" description="Dion Castle -> Front of the Hive Fortress"
		locX="15384" locY="182932" locZ="-3593" price="0" isNoble="false" />
	<teleport id="13011"
		description="Dion Castle -> Front of the Dragonspine Fortress" locX="14480"
		locY="90563" locZ="-3734" price="0" isNoble="false" />
	<teleport id="13012" description="Dion Castle -> Cruma Tower"
		locX="17225" locY="114173" locZ="-3440" price="500" isNoble="false" />
	<teleport id="13013" description="Dion Castle -> Plains of Dion"
		locX="630" locY="179184" locZ="-3720" price="500" isNoble="false" />
	<teleport id="13014" description="Dion Castle -> Bee Hive"
		locX="34475" locY="188095" locZ="-2976" price="500" isNoble="false" />
	<teleport id="13015" description="Dion Castle -> Tanor Canyon"
		locX="58316" locY="163851" locZ="-2816" price="500" isNoble="false" />
	<teleport id="60026" description="Dion Throne" locX="22074"
		locY="160352" locZ="-2690" price="0" isNoble="false" />
	<teleport id="60027" description="Dion Inside" locX="22150"
		locY="158042" locZ="-2873" price="0" isNoble="false" />
	<teleport id="60028" description="Dion Artefacts Room" locX="22078"
		locY="161387" locZ="-2771" price="0" isNoble="false" />
	<teleport id="60029" description="Dion Out of the Castle"
		locX="22306" locY="156027" locZ="-2953" price="0" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/teleport/FortressAaru.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../templates/teleport.xsd">
	<teleport id="12237" description="Aaru Fortress -> Fortress North Gate"
		locX="73205" locY="183893" locZ="-2584" price="0" isNoble="false" />
	<teleport id="12238" description="Aaru Fortress -> Fortress South Gate"
		locX="72822" locY="188128" locZ="-2584" price="0" isNoble="false" />
	<teleport id="12239" description="Aaru Fortress -> Heine Town Square"
		locX="111455" locY="219400" locZ="-3546" price="0" isNoble="false" />
	<teleport id="12240" description="Aaru Fortress -> Giran Town Square"
		locX="81749" locY="149171" locZ="-3464" price="0" isNoble="false" />
	<teleport id="12241" description="Aaru Fortress -> Inside the Garden of Eva"
		locX="82693" locY="242220" locZ="-6712" price="500" isNoble="false" />
	<teleport id="12242" description="Aaru Fortress -> The Center of Alligator Island"
		locX="113708" locY="178387" locZ="-3232" price="500" isNoble="false" />
	<teleport id="12243" description="Aaru Fortress -> Dragon Valley"
		locX="73024" locY="118485" locZ="-3720" price="500" isNoble="false" />
	<teleport id="12244" description="Aaru Fortress -> Tanor Canyon"
		locX="60374" locY="164301" locZ="-2856" price="500" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/teleport/ElvenVillage.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/teleport.xsd">
	<teleport id="2" description="Elven Town  -> Town of Gludio"
		locX="-12672" locY="122776" locZ="-3116" price="9200" isNoble="false" />
	<teleport id="468" description="Elven Village -> Elven Forest"
		locX="21362" locY="51122" locZ="-3688" price="710" isNoble="false" />
	<teleport id="469" description="Elven Village -> Neutral Zone"
		locX="-10674" locY="75550" locZ="-3597" price="740" isNoble="false" />
	<teleport id="470" description="Elven Village -> Elven Fortress"
		locX="29294" locY="74968" locZ="-3776" price="820" isNoble="false" />
	<teleport id="1013" description="Elven Village -> Neutral Zone"
		locX="-10674" locY="75550" locZ="-3597" price="1700" isNoble="false" />
	<teleport id="1014" description="Elven Village -> Dwarven Village"
		locX="115113" locY="-178212" locZ="-901" price="23000" isNoble="false" />
	<teleport id="1015" description="Elven Village -> TI Village"
		locX="-84318" locY="244579" locZ="-3730" price="23000" isNoble="false" />
	<teleport id="1016" description="Elven Village -> Orc Village"
		locX="-44836" locY="-112524" locZ="-235" price="18000" isNoble="false" />
	<teleport id="12053" description="Elven Village -> Kamael Village"
		locX="-117251" locY="46771" locZ="360" price="16000" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/teleport/Hunter.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/teleport.xsd">
	<teleport id="42" description="Hunter's Village -> Giran Town"
		locX="83400" locY="147943" locZ="-3404" price="9400" isNoble="false" />
	<teleport id="43" description="Hunter's Village -> Oren Town"
		locX="82956" locY="53162" locZ="-1495" price="4100" isNoble="false" />
	<teleport id="44" description="Hunter's Village -> Ivory Tower"
		locX="85348" locY="16142" locZ="-3699" price="8200" isNoble="false" />
	<teleport id="45" description="Hunter's Village -> Hardin's Private Academy"
		locX="105918" locY="109759" locZ="-3207" price="3400" isNoble="false" />
	<teleport id="46" description="Hunter's Village -> Aden Town"
		locX="146819" locY="25806" locZ="-2013" price="5900" isNoble="false" />
	<teleport id="99" description="Hunters -> Northern Pathway of Enchanted Valley"
		locX="104426" locY="33746" locZ="-3800" price="3600" isNoble="false" />
	<teleport id="100" description="Hunters -> Southern Pathway of Enchanted Valley"
		locX="124904" locY="61992" locZ="-3920" price="1300" isNoble="false" />
	<teleport id="101" description="Hunters -> Entrance to the Forest of Mirrors"
		locX="142065" locY="81300" locZ="-3000" price="2000" isNoble="false" />
	<teleport id="102" description="Hunters -> The Front of Anghel Waterfall"
		locX="163341" locY="91374" locZ="-3320" price="4000" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/teleport/Cruma.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/teleport.xsd">
	<teleport id="22" description="Cruma Tower 1st floor -> Cruma Tower Entrance"
		locX="17192" locY="114178" locZ="-3439" price="0" isNoble="false" />
	<teleport id="23" description="Cruma Tower 1st floor -> Cruma Tower 2nd floor"
		locX="17776" locY="108288" locZ="-9056" price="0" isNoble="false" />
	<teleport id="24" description="Cruma Tower 2nd floor -> Cruma Tower 1st floor"
		locX="17724" locY="114004" locZ="-11667" price="0" isNoble="false" />
	<teleport id="55" description="Cruma level 2 -> Cruma level 3"
		locX="17719" locY="115590" locZ="-6584" price="0" isNoble="false" />
	<teleport id="56" description="Cruma level 3 -> Cruma Core"
		locX="17691" locY="111726" locZ="-6583" price="0" isNoble="false" />
	<teleport id="57" description="Cruma core -> Cruma level 3"
		locX="17719" locY="115590" locZ="-6584" price="0" isNoble="false" />
	<teleport id="58" description="Cruma Tower 3rd floor -> Cruma Tower 2nd Floor"
		locX="17731" locY="119465" locZ="-9067" price="0" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/teleport/FortressNarsell.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../templates/teleport.xsd">
	<teleport id="12148" description="Narsell Fortress -> Fortress West Gate"
		locX="153112" locY="56872" locZ="-3256" price="0" isNoble="false" />
	<teleport id="12149" description="Narsell Fortress -> Fortress East Gate"
		locX="156730" locY="53921" locZ="-3256" price="0" isNoble="false" />
	<teleport id="12150" description="Narsell Fortress -> Aden Town Square"
		locX="147450" locY="28081" locZ="-2264" price="0" isNoble="false" />
	<teleport id="12151"
		description="Narsell Fortress -> Front of the Aden Castle Gate" locX="147428"
		locY="20161" locZ="-2008" price="0" isNoble="false" />
	<teleport id="12152" description="Narsell Fortress -> Ancient Battleground"
		locX="118509" locY="-4779" locZ="-4000" price="500" isNoble="false" />
	<teleport id="12153"
		description="Narsell Fortress -> Enchanted Valley, Southern Region"
		locX="124904" locY="61992" locZ="-3920" price="500" isNoble="false" />
	<teleport id="12154"
		description="Narsell Fortress -> Enchanted Valley, Northern Region"
		locX="104426" locY="33746" locZ="-3800" price="500" isNoble="false" />
	<teleport id="12155" description="Narsell Fortress -> Blazing Swamp"
		locX="155310" locY="-16339" locZ="-3320" price="500" isNoble="false" />
</list>
