=== KoheNC/l2emu/L2EmuProject-DataPack/data/static_data/templates/teleport.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.l2jfree.com" xmlns="http://www.l2jfree.com"
	elementFormDefault="qualified">
	<xs:include schemaLocation="base.xsd" />
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="teleport" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="teleport">
		<xs:complexType>
			<xs:attribute name="description" use="required" />
			<xs:attribute name="id" use="required" type="xs:integer" />
			<xs:attribute name="isNoble" use="required" type="xs:boolean" />
			<xs:attribute name="locX" use="required" type="xs:integer" />
			<xs:attribute name="locY" use="required" type="xs:integer" />
			<xs:attribute name="locZ" use="required" type="xs:integer" />
			<xs:attribute name="price" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/teleport/Cat.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../templates/teleport.xsd">
	<teleport id="250" description="Cat Heretics Entrance" locX="-53174"
		locY="-250275" locZ="-7911" price="0" isNoble="false" />
	<teleport id="251" description="Cat Heretics Exit" locX="42514"
		locY="143917" locZ="-5385" price="0" isNoble="false" />
	<teleport id="252" description="Cat Branded Entrance" locX="46217"
		locY="170290" locZ="-4983" price="0" isNoble="false" />
	<teleport id="253" description="Cat Branded Exit" locX="45770"
		locY="170299" locZ="-4985" price="0" isNoble="false" />
	<teleport id="254" description="Cat Apostate Entrance" locX="-20230"
		locY="-250780" locZ="-8168" price="0" isNoble="false" />
	<teleport id="255" description="Cat Apostate Exit" locX="77225"
		locY="78362" locZ="-5119" price="0" isNoble="false" />
	<teleport id="256" description="Cat Witch Entrance" locX="140404"
		locY="79678" locZ="-5431" price="0" isNoble="false" />
	<teleport id="257" description="Cat Witch Exit" locX="139965"
		locY="79678" locZ="-5433" price="0" isNoble="false" />
	<teleport id="258" description="Cat DarkOmen Entrance" locX="-19500"
		locY="13508" locZ="-4905" price="0" isNoble="false" />
	<teleport id="259" description="Cat DarkOmen Exit" locX="-19931"
		locY="13502" locZ="-4905" price="0" isNoble="false" />
	<teleport id="260" description="Cat ForbiddenPath Entrance"
		locX="12521" locY="-248481" locZ="-9585" price="0" isNoble="false" />
	<teleport id="261" description="Cat ForbiddenPath Exit" locX="113429"
		locY="84540" locZ="-6545" price="0" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/teleport/Toi.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/teleport.xsd">
	<teleport id="201" description="TOI - 1st Floor" locX="115168"
		locY="16022" locZ="-5100" price="100000" isNoble="false" />
	<teleport id="202" description="TOI - 2nd Floor" locX="114649"
		locY="18587" locZ="-3609" price="150000" isNoble="false" />
	<teleport id="203" description="TOI - 3rd Floor" locX="117918"
		locY="16039" locZ="-2127" price="200000" isNoble="false" />
	<teleport id="204" description="TOI - 4th Floor" locX="114622"
		locY="12946" locZ="-645" price="250000" isNoble="false" />
	<teleport id="205" description="TOI - 5th Floor" locX="112209"
		locY="16078" locZ="928" price="300000" isNoble="false" />
	<teleport id="206" description="TOI - 6th Floor" locX="112376"
		locY="16099" locZ="1947" price="350000" isNoble="false" />
	<teleport id="207" description="TOI - 7th Floor" locX="114448"
		locY="16175" locZ="2994" price="400000" isNoble="false" />
	<teleport id="208" description="TOI - 8th Floor" locX="111063"
		locY="16118" locZ="3967" price="450000" isNoble="false" />
	<teleport id="209" description="TOI - 9th Floor" locX="117147"
		locY="18415" locZ="4977" price="500000" isNoble="false" />
	<teleport id="210" description="TOI - 10th Floor" locX="118374"
		locY="15973" locZ="5987" price="550000" isNoble="false" />
	<teleport id="211" description="TOI - 11th Floor" locX="112209"
		locY="16078" locZ="7028" price="600000" isNoble="false" />
	<teleport id="212" description="TOI - 12th Floor" locX="114809"
		locY="18711" locZ="7996" price="650000" isNoble="false" />
	<teleport id="213" description="TOI - 13th Floor" locX="115178"
		locY="16989" locZ="9007" price="700000" isNoble="false" />
	<teleport id="214" description="TOI - 14th Floor Outside Door"
		locX="112714" locY="14111" locZ="10077" price="800000" isNoble="false" />
	<teleport id="215" description="TOI - 14th Floor Inside On Roof"
		locX="113098" locY="14532" locZ="10077" price="900000" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/teleport/Heine.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/teleport.xsd">
	<teleport id="59" description="Heine -> The Town of Giran"
		locX="83400" locY="147943" locZ="-3404" price="7600" isNoble="false" />
	<teleport id="60" description="Heine -> Giran Harbor" locX="47942"
		locY="186764" locZ="-3485" price="7100" isNoble="false" />
	<teleport id="65" description="Heine -> The Town of Dion"
		locX="15670" locY="142983" locZ="-2705" price="12000" isNoble="false" />
	<teleport id="66" description="Heine -> Field of Silence"
		locX="87691" locY="162835" locZ="-3520" price="12000" isNoble="false" />
	<teleport id="67" description="Heine -> Field of Whispers"
		locX="82192" locY="226128" locZ="-3656" price="5900" isNoble="false" />
	<teleport id="68" description="Heine -> Entrance to Alligator Islands"
		locX="115583" locY="192261" locZ="-3488" price="2100" isNoble="false" />
	<teleport id="1063" description="Heine -> Oren" locX="82956"
		locY="53162" locZ="-1495" price="50000" isNoble="false" />
	<teleport id="1064" description="Heine -> Aden" locX="146331"
		locY="25806" locZ="-2013" price="50000" isNoble="false" />
	<teleport id="1065" description="Heine -> Goddard" locX="147928"
		locY="-55273" locZ="-2734" price="83000" isNoble="false" />
	<teleport id="1066" description="Heine -> Rune" locX="43799"
		locY="-47727" locZ="-798" price="82000" isNoble="false" />
	<teleport id="1067" description="Heine -> Schuttgart" locX="87386"
		locY="-143246" locZ="-1293" price="100000" isNoble="false" />
	<teleport id="1068" description="Heine -> Gludio" locX="-12672"
		locY="122776" locZ="-3116" price="47000" isNoble="false" />
	<teleport id="1069" description="Heine -> Garden of Eva" locX="86006"
		locY="231069" locZ="-3600" price="2400" isNoble="false" />
	<teleport id="200918" description="Heine -> Isle of Prayer"
		locX="149518" locY="195280" locZ="-3736" price="7200" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/static_data/teleport/DwarvenVillage.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../templates/teleport.xsd">
	<teleport id="16" description="Dwarven Town  -> Town of Gludio"
		locX="-12787" locY="122779" locZ="-3112" price="32000" isNoble="false" />
	<teleport id="17"
		description="Dwarven Town -> Eastern Mining Zone (Northeastern Shore)"
		locX="169008" locY="-208272" locZ="-3504" price="2400" isNoble="false" />
	<teleport id="137" description="Dwarven Town -> Mithril Mines Eastern Entrance"
		locX="178591" locY="-184615" locZ="-360" price="12000" isNoble="false" />
	<teleport id="418" description="Dwarven Town -> Abandoned Coal Mines"
		locX="139714" locY="-177456" locZ="-1536" price="690" isNoble="false" />
	<teleport id="419" description="Dwarven Town -> Mithril Mines Western Entrance"
		locX="171946" locY="-173352" locZ="3440" price="11000" isNoble="false" />
	<teleport id="1017" description="Dwarven Village -> DE Village"
		locX="9709" locY="15566" locZ="-4568" price="22000" isNoble="false" />
	<teleport id="1018" description="Dwarven Village -> Elven Village"
		locX="46951" locY="51550" locZ="-2976" price="23000" isNoble="false" />
	<teleport id="1019" description="Dwarven Village -> TI Village"
		locX="-84141" locY="244623" locZ="-3728" price="46000" isNoble="false" />
	<teleport id="1020" description="Dwarven Village -> Schuttgart"
		locX="87126" locY="-143520" locZ="-1288" price="4400" isNoble="false" />
	<teleport id="1021" description="Dwarven Village -> Orc Village"
		locX="-45158" locY="-112583" locZ="-240" price="17000" isNoble="false" />
	<teleport id="1022"
		description="Dwarven Village -> Western Mining Zone (Central Shore)"
		locX="136910" locY="-205082" locZ="-3664" price="970" isNoble="false" />
	<teleport id="12056" description="Dwarven Village -> Kamael Village"
		locX="-117251" locY="46771" locZ="360" price="32000" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/teleport/FortDragonspine.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../templates/teleport.xsd">
	<teleport id="12100" description="Dragonspine Fort -> Fort North Gate"
		locX="12497" locY="93855" locZ="-3425" price="0" isNoble="false" />
	<teleport id="12101" description="Dragonspine Fort -> Fort South Gate"
		locX="10486" locY="96307" locZ="-3425" price="0" isNoble="false" />
	<teleport id="12102" description="Dragonspine Fort -> Dion Town Square"
		locX="18748" locY="145437" locZ="-3127" price="0" isNoble="false" />
	<teleport id="12103" description="Dragonspine Fort -> Oren Town Square"
		locX="82321" locY="55139" locZ="-1524" price="0" isNoble="false" />
	<teleport id="12104" description="Dragonspine Fort -> The Ant Nest"
		locX="-25832" locY="173118" locZ="-4154" price="500" isNoble="false" />
	<teleport id="12105" description="Dragonspine Fort -> Windawood Manor"
		locX="-25791" locY="162013" locZ="-2528" price="500" isNoble="false" />
	<teleport id="12106" description="Dragonspine Fort -> Sea of Spores"
		locX="62425" locY="30856" locZ="-3774" price="500" isNoble="false" />
	<teleport id="12107" description="Dragonspine Fort -> Ancient Battleground"
		locX="108264" locY="-2846" locZ="-3428" price="500" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/teleport/FortMonastic.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/teleport.xsd">
	<teleport id="12140" description="Monastic Fort -> Fortress North Gate"
		locX="72388" locY="-96770" locZ="-1424" price="0" isNoble="false" />
	<teleport id="12141" description="Monastic Fort -> Fortress South Gate"
		locX="71937" locY="-92600" locZ="-1416" price="0" isNoble="false" />
	<teleport id="12142" description="Monastic Fort -> Rune Town Square"
		locX="43889" locY="-49101" locZ="-792" price="0" isNoble="false" />
	<teleport id="12143" description="Monastic Fort -> Schuttgart Town Square"
		locX="87379" locY="-142322" locZ="-1336" price="0" isNoble="false" />
	<teleport id="12144" description="Monastic Fort -> Swamp of Screams"
		locX="69340" locY="-50203" locZ="-3288" price="500" isNoble="false" />
	<teleport id="12145" description="Monastic Fort -> Valley of Saints"
		locX="65307" locY="-71445" locZ="-3688" price="500" isNoble="false" />
	<teleport id="12146" description="Monastic Fort -> Den of Evil"
		locX="68693" locY="-110438" locZ="-1904" price="500" isNoble="false" />
	<teleport id="12147" description="Monastic Fort -> Frozen Labyrinth"
		locX="113910" locY="-108732" locZ="-848" price="500" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/static_data/teleport/FortressWestern.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../templates/teleport.xsd">
	<teleport id="12196" description="Western Fortress -> Fort North Gate"
		locX="112320" locY="-17152" locZ="-992" price="0" isNoble="false" />
	<teleport id="12197" description="Western Fortress -> Fort South Gate"
		locX="110339" locY="-13257" locZ="-992" price="0" isNoble="false" />
	<teleport id="12198" description="Western Fortress -> Goddard Town Square"
		locX="147725" locY="-56517" locZ="-2775" price="0" isNoble="false" />
	<teleport id="12199" description="Western Fortress -> Goddard Town Gate"
		locX="147876" locY="-42345" locZ="-2208" price="0" isNoble="false" />
	<teleport id="12200" description="Western Fortress -> Aden Town Square"
		locX="146331" locY="25762" locZ="-2018" price="500" isNoble="false" />
	<teleport id="12201" description="Western Fortress -> Blazing Swamp"
		locX="155305" locY="-16326" locZ="-3315" price="500" isNoble="false" />
	<teleport id="12202" description="Western Fortress -> Varka Silenos Outpost"
		locX="125556" locY="-40951" locZ="-3719" price="500" isNoble="false" />
	<teleport id="12203" description="Western Fortress -> Tower of Insolence"
		locX="114642" locY="11103" locZ="-5115" price="500" isNoble="false" />
</list>

=== KoheNC/l2emu/L2EmuProject-DataPack/data/npc_data/teleport/FortDemon.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.l2jfree.com ../../templates/teleport.xsd">
	<teleport id="12110" description="Demon Fort -> Fortress West Gate"
		locX="98920" locY="-56423" locZ="-624" price="0" isNoble="false" />
	<teleport id="12111" description="Demon Fort -> Fortress East Gate"
		locX="102390" locY="-54320" locZ="-632" price="0" isNoble="false" />
	<teleport id="12112" description="Demon Fort -> Rune Town Square"
		locX="43889" locY="-49101" locZ="-792" price="0" isNoble="false" />
	<teleport id="12113" description="Demon Fort -> Goddard Town Square"
		locX="147728" locY="-56331" locZ="-2776" price="0" isNoble="false" />
	<teleport id="12114" description="Demon Fort -> Swamp of Screams"
		locX="69340" locY="-50203" locZ="-3288" price="500" isNoble="false" />
	<teleport id="12115" description="Demon Fort -> Valley of Saints"
		locX="65307" locY="-71445" locZ="-3688" price="500" isNoble="false" />
	<teleport id="12116" description="Demon Fort -> Entrance to the Forge of the Gods"
		locX="169018" locY="-116303" locZ="-2432" price="500" isNoble="false" />
	<teleport id="12117" description="Demon Fort -> Wall of Argos"
		locX="165054" locY="-47861" locZ="-3560" price="500" isNoble="false" />
</list>
